export interface Hero {
  id: string;
  name: string;
  img: string;
  wr: string;
  role: 'carry' | 'mid' | 'offlane' | 'support';
  color: string;
}

export const HEROES_LIST: Hero[] = [
  // CARRY (Керри)
  { id: "1", name: "Anti-Mage", img: "antimage", wr: "48.5", role: "carry", color: "from-purple-900/60" },
  { id: "4", name: "Bloodseeker", img: "bloodseeker", wr: "50.4", role: "carry", color: "from-red-900/60" },
  { id: "6", name: "Drow Ranger", img: "drow_ranger", wr: "50.1", role: "carry", color: "from-blue-900/40" },
  { id: "8", name: "Juggernaut", img: "juggernaut", wr: "49.2", role: "carry", color: "from-orange-600/40" },
  { id: "10", name: "Morphling", img: "morphling", wr: "46.5", role: "carry", color: "from-cyan-700/40" },
  { id: "12", name: "Phantom Lancer", img: "phantom_lancer", wr: "49.0", role: "carry", color: "from-blue-800/40" },
  { id: "15", name: "Razor", img: "razor", wr: "50.2", role: "carry", color: "from-blue-400/40" },
  { id: "18", name: "Sven", img: "sven", wr: "51.0", role: "carry", color: "from-blue-900/60" },
  { id: "32", name: "Riki", img: "riki", wr: "52.4", role: "carry", color: "from-purple-900/40" },
  { id: "41", name: "Faceless Void", img: "faceless_void", wr: "49.8", role: "carry", color: "from-purple-900/60" },
  { id: "42", name: "Wraith King", img: "skeleton_king", wr: "53.1", role: "carry", color: "from-green-900/60" },
  { id: "44", name: "Phantom Assassin", img: "phantom_assassin", wr: "48.9", role: "carry", color: "from-cyan-900/60" },
  { id: "48", name: "Luna", img: "luna", wr: "51.7", role: "carry", color: "from-blue-950/60" },
  { id: "54", name: "Lifestealer", img: "life_stealer", wr: "51.1", role: "carry", color: "from-red-900/60" },
  { id: "56", name: "Clinkz", img: "clinkz", wr: "52.0", role: "carry", color: "from-orange-900/60" },
  { id: "63", name: "Weaver", img: "weaver", wr: "51.3", role: "carry", color: "from-red-800/40" },
  { id: "67", name: "Spectre", img: "spectre", wr: "54.1", role: "carry", color: "from-purple-950/80" },
  { id: "70", name: "Ursa", img: "ursa", wr: "52.3", role: "carry", color: "from-red-900/40" },
  { id: "72", name: "Gyrocopter", img: "gyrocopter", wr: "49.5", role: "carry", color: "from-slate-700/40" },
  { id: "73", name: "Alchemist", img: "alchemist", wr: "48.2", role: "carry", color: "from-yellow-900/40" },
  { id: "80", name: "Lone Druid", img: "lone_druid", wr: "51.0", role: "carry", color: "from-green-900/40" },
  { id: "81", name: "Chaos Knight", img: "chaos_knight", wr: "52.8", role: "carry", color: "from-red-950/80" },
  { id: "89", name: "Naga Siren", img: "naga_siren", wr: "50.3", role: "carry", color: "from-blue-800/40" },
  { id: "93", name: "Slark", img: "slark", wr: "51.9", role: "carry", color: "from-blue-900/60" },
  { id: "94", name: "Medusa", img: "medusa", wr: "51.4", role: "carry", color: "from-green-800/40" },
  { id: "95", name: "Troll Warlord", img: "troll_warlord", wr: "49.2", role: "carry", color: "from-red-900/40" },
  { id: "109", name: "Terrorblade", img: "terrorblade", wr: "47.4", role: "carry", color: "from-blue-950/80" },
  { id: "126", name: "Muerta", img: "muerta", wr: "50.5", role: "carry", color: "from-cyan-900/60" },

  // MID (Мидеры)
  { id: "11", name: "Shadow Fiend", img: "nevermore", wr: "50.1", role: "mid", color: "from-red-950/90" },
  { id: "13", name: "Puck", img: "puck", wr: "51.2", role: "mid", color: "from-purple-800/60" },
  { id: "17", name: "Storm Spirit", img: "storm_spirit", wr: "48.2", role: "mid", color: "from-blue-700/50" },
  { id: "21", name: "Windranger", img: "windrunner", wr: "50.6", role: "mid", color: "from-green-700/40" },
  { id: "22", name: "Zeus", img: "zuus", wr: "53.4", role: "mid", color: "from-blue-400/40" },
  { id: "23", name: "Kunkka", img: "kunkka", wr: "49.8", role: "mid", color: "from-blue-900/60" },
  { id: "25", name: "Lina", img: "lina", wr: "52.3", role: "mid", color: "from-orange-700/60" },
  { id: "34", name: "Tinker", img: "tinker", wr: "46.8", role: "mid", color: "from-purple-900/40" },
  { id: "35", name: "Sniper", img: "sniper", wr: "50.5", role: "mid", color: "from-slate-800/40" },
  { id: "39", name: "Queen of Pain", img: "queenofpain", wr: "48.9", role: "mid", color: "from-red-900/60" },
  { id: "43", name: "Death Prophet", img: "death_prophet", wr: "51.2", role: "mid", color: "from-green-900/40" },
  { id: "45", name: "Pugna", img: "pugna", wr: "50.3", role: "mid", color: "from-green-600/40" },
  { id: "46", name: "Templar Assassin", img: "templar_assassin", wr: "50.8", role: "mid", color: "from-purple-900/40" },
  { id: "47", name: "Viper", img: "viper", wr: "52.6", role: "mid", color: "from-green-900/60" },
  { id: "49", name: "Dragon Knight", img: "dragon_knight", wr: "51.4", role: "mid", color: "from-red-900/60" },
  { id: "52", name: "Leshrac", img: "leshrac", wr: "51.5", role: "mid", color: "from-blue-500/40" },
  { id: "59", name: "Huskar", img: "huskar", wr: "50.4", role: "mid", color: "from-orange-950/80" },
  { id: "65", name: "Batrider", img: "batrider", wr: "48.1", role: "mid", color: "from-orange-900/60" },
  { id: "74", name: "Invoker", img: "invoker", wr: "47.8", role: "mid", color: "from-orange-400/30" },
  { id: "76", name: "Outworld Destroyer", img: "obsidian_destroyer", wr: "53.2", role: "mid", color: "from-blue-950/80" },
  { id: "82", name: "Meepo", img: "meepo", wr: "54.7", role: "mid", color: "from-yellow-900/40" },
  { id: "106", name: "Ember Spirit", img: "ember_spirit", wr: "49.3", role: "mid", color: "from-red-800/60" },
  { id: "107", name: "Earth Spirit", img: "earth_spirit", wr: "45.1", role: "mid", color: "from-green-900/40" },
  { id: "113", name: "Arc Warden", img: "arc_warden", wr: "52.1", role: "mid", color: "from-blue-900/60" },
  { id: "120", name: "Pangolier", img: "pangolier", wr: "47.1", role: "mid", color: "from-red-700/40" },
  { id: "129", name: "Void Spirit", img: "void_spirit", wr: "48.7", role: "mid", color: "from-purple-900/60" },

  // OFFLANE (Сложная линия)
  { id: "2", name: "Axe", img: "axe", wr: "52.1", role: "offlane", color: "from-red-900/60" },
  { id: "14", name: "Pudge", img: "pudge", wr: "53.1", role: "offlane", color: "from-green-900/60" },
  { id: "16", name: "Sand King", img: "sand_king", wr: "52.1", role: "offlane", color: "from-orange-900/40" },
  { id: "19", name: "Tiny", img: "tiny", wr: "47.5", role: "offlane", color: "from-slate-700/40" },
  { id: "28", name: "Slardar", img: "slardar", wr: "53.5", role: "offlane", color: "from-blue-900/60" },
  { id: "29", name: "Tidehunter", img: "tidehunter", wr: "51.8", role: "offlane", color: "from-green-900/40" },
  { id: "33", name: "Enigma", img: "enigma", wr: "49.1", role: "offlane", color: "from-purple-950/80" },
  { id: "36", name: "Necrophos", img: "necrolyte", wr: "52.7", role: "offlane", color: "from-green-600/40" },
  { id: "38", name: "Beastmaster", img: "beastmaster", wr: "48.8", role: "offlane", color: "from-yellow-900/40" },
  { id: "53", name: "Nature's Prophet", img: "furion", wr: "46.2", role: "offlane", color: "from-green-900/60" },
  { id: "55", name: "Dark Seer", img: "dark_seer", wr: "54.2", role: "offlane", color: "from-purple-900/40" },
  { id: "60", name: "Night Stalker", img: "night_stalker", wr: "52.9", role: "offlane", color: "from-blue-950/80" },
  { id: "61", name: "Broodmother", img: "broodmother", wr: "47.8", role: "offlane", color: "from-red-950/80" },
  { id: "69", name: "Doom", img: "doom_bringer", wr: "47.5", role: "offlane", color: "from-red-950/90" },
  { id: "71", name: "Spirit Breaker", img: "spirit_breaker", wr: "52.8", role: "offlane", color: "from-blue-900/80" },
  { id: "77", name: "Lycan", img: "lycan", wr: "51.3", role: "offlane", color: "from-red-900/40" },
  { id: "78", name: "Brewmaster", img: "brewmaster", wr: "52.6", role: "offlane", color: "from-orange-800/40" },
  { id: "85", name: "Undying", img: "undying", wr: "52.6", role: "offlane", color: "from-green-950/80" },
  { id: "92", name: "Visage", img: "visage", wr: "53.6", role: "offlane", color: "from-cyan-950/80" },
  { id: "96", name: "Centaur Warrunner", img: "centaur", wr: "53.8", role: "offlane", color: "from-red-900/40" },
  { id: "97", name: "Magnus", img: "magnus", wr: "48.1", role: "offlane", color: "from-blue-800/40" },
  { id: "98", name: "Timbersaw", img: "timbersaw", wr: "49.7", role: "offlane", color: "from-orange-900/60" },
  { id: "99", name: "Bristleback", img: "bristleback", wr: "51.3", role: "offlane", color: "from-orange-800/40" },
  { id: "102", name: "Abaddon", img: "abaddon", wr: "53.1", role: "offlane", color: "from-cyan-950/80" },
  { id: "104", name: "Legion Commander", img: "legion_commander", wr: "50.9", role: "offlane", color: "from-red-800/60" },
  { id: "108", name: "Underlord", img: "abyssal_underlord", wr: "54.2", role: "offlane", color: "from-green-950/80" },
  { id: "135", name: "Dawnbreaker", img: "dawnbreaker", wr: "51.2", role: "offlane", color: "from-orange-700/60" },
  { id: "137", name: "Primal Beast", img: "primal_beast", wr: "50.8", role: "offlane", color: "from-red-900/60" },

  // SUPPORT (Саппорты)
  { id: "3", name: "Bane", img: "bane", wr: "51.1", role: "support", color: "from-purple-950/80" },
  { id: "5", name: "Crystal Maiden", img: "crystal_maiden", wr: "52.9", role: "support", color: "from-blue-500/40" },
  { id: "7", name: "Earthshaker", img: "earthshaker", wr: "50.3", role: "support", color: "from-orange-900/40" },
  { id: "9", name: "Mirana", img: "mirana", wr: "48.7", role: "support", color: "from-blue-300/30" },
  { id: "20", name: "Vengeful Spirit", img: "vengefulspirit", wr: "52.7", role: "support", color: "from-blue-900/60" },
  { id: "26", name: "Lion", img: "lion", wr: "49.1", role: "support", color: "from-red-900/40" },
  { id: "27", name: "Shadow Shaman", img: "shadow_shaman", wr: "51.0", role: "support", color: "from-yellow-700/40" },
  { id: "30", name: "Witch Doctor", img: "witch_doctor", wr: "54.5", role: "support", color: "from-purple-800/40" },
  { id: "31", name: "Lich", img: "lich", wr: "53.2", role: "support", color: "from-blue-600/40" },
  { id: "37", name: "Warlock", img: "warlock", wr: "54.8", role: "support", color: "from-red-950/80" },
  { id: "40", name: "Venomancer", img: "venomancer", wr: "51.6", role: "support", color: "from-green-600/40" },
  { id: "50", name: "Dazzle", img: "dazzle", wr: "50.3", role: "support", color: "from-purple-600/40" },
  { id: "51", name: "Clockwerk", img: "rattletrap", wr: "50.7", role: "support", color: "from-orange-800/60" },
  { id: "57", name: "Omniknight", img: "omniknight", wr: "53.5", role: "support", color: "from-blue-200/40" },
  { id: "58", name: "Enchantress", img: "enchantress", wr: "49.4", role: "support", color: "from-green-400/40" },
  { id: "62", name: "Bounty Hunter", img: "bounty_hunter", wr: "50.8", role: "support", color: "from-red-900/40" },
  { id: "64", name: "Jakiro", img: "jakiro", wr: "52.9", role: "support", color: "from-blue-900/60" },
  { id: "66", name: "Chen", img: "chen", wr: "53.4", role: "support", color: "from-yellow-600/30" },
  { id: "68", name: "Ancient Apparition", img: "ancient_apparition", wr: "51.9", role: "support", color: "from-blue-400/40" },
  { id: "75", name: "Silencer", img: "silencer", wr: "50.2", role: "support", color: "from-purple-800/40" },
  { id: "79", name: "Shadow Demon", img: "shadow_demon", wr: "49.5", role: "support", color: "from-purple-950/80" },
  { id: "83", name: "Treant Protector", img: "treant", wr: "52.1", role: "support", color: "from-green-900/60" },
  { id: "84", name: "Ogre Magi", img: "ogre_magi", wr: "51.4", role: "support", color: "from-blue-700/40" },
  { id: "86", name: "Rubick", img: "rubick", wr: "47.2", role: "support", color: "from-green-400/30" },
  { id: "87", name: "Disruptor", img: "disruptor", wr: "50.9", role: "support", color: "from-blue-600/40" },
  { id: "88", name: "Nyx Assassin", img: "nyx_assassin", wr: "51.5", role: "support", color: "from-cyan-900/40" },
  { id: "90", name: "Keeper of the Light", img: "keeper_of_the_light", wr: "49.1", role: "support", color: "from-yellow-400/30" },
  { id: "91", name: "Io", img: "wisp", wr: "48.2", role: "support", color: "from-blue-400/40" },
  { id: "100", name: "Tusk", img: "tusk", wr: "48.9", role: "support", color: "from-blue-400/40" },
  { id: "101", name: "Skywrath Mage", img: "skywrath_mage", wr: "51.1", role: "support", color: "from-blue-600/40" },
  { id: "103", name: "Elder Titan", img: "elder_titan", wr: "52.4", role: "support", color: "from-orange-900/40" },
  { id: "105", name: "Techies", img: "techies", wr: "49.8", role: "support", color: "from-orange-600/40" },
  { id: "110", name: "Phoenix", img: "phoenix", wr: "51.7", role: "support", color: "from-orange-900/80" },
  { id: "111", name: "Oracle", img: "oracle", wr: "50.2", role: "support", color: "from-purple-400/40" },
  { id: "112", name: "Winter Wyvern", img: "winter_wyvern", wr: "51.5", role: "support", color: "from-blue-400/40" },
  { id: "119", name: "Dark Willow", img: "dark_willow", wr: "49.3", role: "support", color: "from-purple-900/40" },
  { id: "121", name: "Grimstroke", img: "grimstroke", wr: "49.3", role: "support", color: "from-red-950/80" },
  { id: "123", name: "Hoodwink", img: "hoodwink", wr: "51.0", role: "support", color: "from-orange-900/40" },
  { id: "136", name: "Marci", img: "marci", wr: "48.4", role: "support", color: "from-orange-400/40" }
];

export const getHeroColor = (hero: Hero) => {
  if (hero.color) return hero.color;
  const roleColors = {
    carry: "from-blue-900/40",
    mid: "from-red-900/40",
    offlane: "from-green-900/40",
    support: "from-yellow-900/40"
  };
  return roleColors[hero.role] || "from-slate-900/40";
};